import { CarpoolTrip, UserProfile } from '@/types/carpool';

// Current logged-in user profile (Xi'an Evergrande resident)
export const currentUserProfile: UserProfile = {
  id: 'usr_me_001',
  name: '林远 (业主)',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  gender: 'male',
  phone: '187****1167',
  isVerifiedOwner: true,
  communityPhase: '恒大文旅城·二期天际星座',
  roomNumber: '7号楼2单元1802',
  creditScore: 100,
  completedTripsCount: 42,
  identityTag: '高新华为·认证业主',
};

// Preset hot spots in Evergrande Cultural Tourism City
export const EVERGRANDE_ORIGIN_SPOTS = [
  { name: '恒大文旅城·1期天际星空门岗', detail: '1期东主入口人行闸机旁', zone: '恒大文旅城' },
  { name: '恒大文旅城·2期童世界大道主大门', detail: '2期天际星座东门喷泉广场', zone: '恒大文旅城' },
  { name: '恒大文旅城·3期童梦汇南门', detail: '童梦汇商业广场南侧下客区', zone: '恒大文旅城' },
  { name: '恒大文旅城·4期公馆东大门', detail: '公馆东门岗保安亭旁', zone: '恒大文旅城' },
  { name: '恒大文旅城·风情商业街西广场', detail: '西侧公交临时接驳站', zone: '恒大文旅城' },
  { name: '恒大文旅城·运动中心南侧停车场', detail: '文体中心地面充电桩处', zone: '恒大文旅城' },
];

// Preset hot destination spots in Xi'an city
export const XIAN_CITY_DESTINATIONS = [
  // 高新区
  { name: '高新·软件新城 (环普科技园/阿里巴巴)', detail: '天谷八路与云水一路十字', zone: '高新区' },
  { name: '高新·绿地中央广场/保利中心', detail: '锦业路与丈八一路交叉口', zone: '高新区' },
  { name: '高新·都市之门/科技二路', detail: '科技二路与唐延路交汇处', zone: '高新区' },
  { name: '高新·华为西安研究所/中软国际', detail: '西太路与信息大道交汇处', zone: '高新区' },
  // 地铁接驳站
  { name: '地铁2号线·运动公园站 (A/D口)', detail: '未央路与凤城十路十字', zone: '地铁接驳' },
  { name: '地铁2/4/14号线·西安北站 (北广场)', detail: '高铁北客站北侧落客平台', zone: '地铁接驳' },
  { name: '地铁4号线·行政中心站', detail: '凤城八路与未央路交汇处', zone: '地铁接驳' },
  { name: '地铁14号线·秦汉新城站/机场线', detail: '兰池大道地铁站出入口', zone: '地铁接驳' },
  // 经开区
  { name: '经开·西安市行政中心/城市运动公园', detail: '张家堡转盘西北角', zone: '经开区' },
  { name: '经开·汉神购物广场/凤城八路', detail: '文景路与凤城八路十字', zone: '经开区' },
  // 曲江 / 雁塔 / 钟楼
  { name: '曲江·大雁塔北广场/大唐不夜城', detail: '雁塔北路与雁引路交口', zone: '雁塔曲江' },
  { name: '雁塔·小寨十字 (赛格国际购物中心)', detail: '长安中路与小寨东路交口', zone: '钟楼小寨' },
  { name: '莲湖·钟楼/西大街百盛', detail: '北大街与东大街中心盘道', zone: '钟楼小寨' },
];

export const INITIAL_TRIPS: CarpoolTrip[] = [
  {
    id: 'trip_001',
    type: 'driver_offer',
    direction: 'into_city',
    publisher: {
      id: 'usr_drv_101',
      name: '张宇轩 (邻里车主)',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      gender: 'male',
      phone: '138****5621',
      isVerifiedOwner: true,
      communityPhase: '恒大文旅城·1期天际星空',
      roomNumber: '3号楼1单元1204',
      creditScore: 99,
      completedTripsCount: 68,
      identityTag: '高新环普·资深工程师',
    },
    origin: {
      name: '恒大文旅城·1期天际星空门岗',
      detail: '东门保安岗亭处集合',
      zone: '恒大文旅城',
    },
    destination: {
      name: '高新·软件新城 (环普科技园)',
      detail: '天谷八路A座落客区',
      zone: '高新区',
    },
    waypoints: [
      { id: 'wp_1', name: '文旅城2期主大门', estimatedTime: '07:35', isPickupAllowed: true },
      { id: 'wp_2', name: '正阳大道快速路口', estimatedTime: '07:45', isPickupAllowed: false },
      { id: 'wp_3', name: '西安绕城高速丈八收费站', estimatedTime: '08:20', isPickupAllowed: true },
      { id: 'wp_4', name: '软件新城二期西门', estimatedTime: '08:35', isPickupAllowed: true },
    ],
    departureDate: '2026-08-16',
    departureTime: '07:30',
    isRecurring: true,
    recurringDays: ['周一', '周二', '周三', '周四', '周五'],
    totalSeats: 3,
    availableSeats: 2,
    carInfo: {
      brandModel: '特斯拉 Model Y 纯黑版',
      color: '曜石黑',
      plateMasked: '陕A·D***8',
      energyType: 'ev',
    },
    preferences: ['准时发车', '禁烟', '走正阳大道+绕城高速', '后排宽松舒适', '空调适宜'],
    routeHighway: '正阳大道 ➔ 绕城高速 ➔ 丈八立交 ➔ 软件新城',
    estimatedMinutes: 55,
    estimatedDistanceKm: 46.5,
    remark: '工作日每天7:30准时出发，走ETC高速直达高新软件新城，后排只坐两人保证舒适，欢迎同在软件新城/环普上班的邻居拼车！',
    status: 'active',
    createdAt: '2026-08-15 07:10',
    bookings: [
      {
        id: 'bk_001',
        tripId: 'trip_001',
        passengerId: 'usr_pas_201',
        passengerName: '王晓雯',
        passengerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
        passengerPhone: '159****8823',
        communityPhase: '恒大文旅城·1期',
        seatsBooked: 1,
        pickupPoint: '恒大文旅城·1期天际星空门岗',
        dropoffPoint: '软件新城A座',
        notes: '带一个双肩包，会提前5分钟在东门等',
        status: 'confirmed',
        createdAt: '2026-08-15 07:20',
        boardingCode: '852914',
      },
    ],
  },
  {
    id: 'trip_002',
    type: 'driver_offer',
    direction: 'metro_transfer',
    publisher: {
      id: 'usr_drv_102',
      name: '陈思远 (邻里车主)',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      gender: 'male',
      phone: '136****9912',
      isVerifiedOwner: true,
      communityPhase: '恒大文旅城·2期天际星座',
      roomNumber: '5号楼1801',
      creditScore: 98,
      completedTripsCount: 35,
      identityTag: '经开金融·认证业主',
    },
    origin: {
      name: '恒大文旅城·2期童世界大道主大门',
      detail: '喷泉广场西侧临时停车位',
      zone: '恒大文旅城',
    },
    destination: {
      name: '地铁2号线·运动公园站 (D口)',
      detail: '未央路地铁口下车即进站',
      zone: '地铁接驳',
    },
    waypoints: [
      { id: 'wp_201', name: '恒大文旅城商业街', estimatedTime: '07:15', isPickupAllowed: true },
      { id: 'wp_202', name: '西铜快速干线', estimatedTime: '07:25', isPickupAllowed: false },
      { id: 'wp_203', name: '运动公园站D口', estimatedTime: '07:45', isPickupAllowed: true },
    ],
    departureDate: '2026-08-16',
    departureTime: '07:10',
    isRecurring: true,
    recurringDays: ['周一', '周二', '周三', '周四', '周五'],
    totalSeats: 3,
    availableSeats: 3,
    carInfo: {
      brandModel: '比亚迪 汉EV 尊贵版',
      color: '雪域白',
      plateMasked: '陕A·F***3',
      energyType: 'ev',
    },
    preferences: ['地铁快速接驳', '禁烟', '走西铜高架', '35分钟直达地铁口'],
    routeHighway: '西铜快速干线 ➔ 未央立交 ➔ 运动公园站',
    estimatedMinutes: 35,
    estimatedDistanceKm: 28.2,
    remark: '早班急需赶地铁2号线的邻居可上车，全程高架不堵车，到运动公园站换乘极速进市区！',
    status: 'active',
    createdAt: '2026-08-15 06:45',
    bookings: [],
  },
  {
    id: 'trip_003',
    type: 'driver_offer',
    direction: 'into_city',
    publisher: {
      id: 'usr_drv_103',
      name: '李敏娜 (邻里车主)',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      gender: 'female',
      phone: '139****1182',
      isVerifiedOwner: true,
      communityPhase: '恒大文旅城·3期童梦汇',
      roomNumber: '11号楼1单元0601',
      creditScore: 100,
      completedTripsCount: 54,
      identityTag: '锦业路外企·认证业主',
    },
    origin: {
      name: '恒大文旅城·3期童梦汇南门',
      detail: '南门下客区等候',
      zone: '恒大文旅城',
    },
    destination: {
      name: '高新·绿地中央广场/保利中心',
      detail: '锦业路绿地双子塔地面落客',
      zone: '高新区',
    },
    waypoints: [
      { id: 'wp_301', name: '文旅城公馆东门', estimatedTime: '07:45', isPickupAllowed: true },
      { id: 'wp_302', name: '高新锦业一路', estimatedTime: '08:40', isPickupAllowed: true },
      { id: 'wp_303', name: '绿地中央广场', estimatedTime: '08:45', isPickupAllowed: true },
    ],
    departureDate: '2026-08-16',
    departureTime: '07:40',
    isRecurring: true,
    recurringDays: ['周一', '周二', '周三', '周四', '周五'],
    totalSeats: 2,
    availableSeats: 1,
    carInfo: {
      brandModel: '理想 L7 Max 银灰',
      color: '星环银',
      plateMasked: '陕A·D***1',
      energyType: 'hybrid',
    },
    preferences: ['女士优先', '禁烟', '静音车厢', '真皮大座椅', '后排独立温控'],
    routeHighway: '正阳大道 ➔ 绕城高速南段 ➔ 锦业路出口',
    estimatedMinutes: 60,
    estimatedDistanceKm: 48.0,
    remark: '本人去锦业路保利中心上班，车内干净卫生，配瓶装水，欢迎文旅城3期和公馆的邻里同行。',
    status: 'active',
    createdAt: '2026-08-15 07:30',
    bookings: [
      {
        id: 'bk_002',
        tripId: 'trip_003',
        passengerId: 'usr_pas_202',
        passengerName: '刘佳欣',
        passengerAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
        passengerPhone: '186****9012',
        communityPhase: '恒大文旅城·3期',
        seatsBooked: 1,
        pickupPoint: '恒大文旅城·3期童梦汇南门',
        dropoffPoint: '高新绿地领海大厦',
        notes: '非常准时，感谢邻居车主！',
        status: 'confirmed',
        createdAt: '2026-08-15 07:35',
        boardingCode: '614920',
      },
    ],
  },
  {
    id: 'trip_004',
    type: 'passenger_request',
    direction: 'into_city',
    publisher: {
      id: 'usr_pas_301',
      name: '赵子豪 (求拼车)',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
      gender: 'male',
      phone: '150****3390',
      isVerifiedOwner: true,
      communityPhase: '恒大文旅城·4期公馆',
      roomNumber: '2号楼1单元1403',
      creditScore: 97,
      completedTripsCount: 19,
      identityTag: '经开行政中心·公务职员',
    },
    origin: {
      name: '恒大文旅城·4期公馆东大门',
      detail: '东门岗随时可出发',
      zone: '恒大文旅城',
    },
    destination: {
      name: '经开·西安市行政中心/城市运动公园',
      detail: '凤城八路市委北门',
      zone: '经开区',
    },
    waypoints: [],
    departureDate: '2026-08-16',
    departureTime: '07:50',
    isRecurring: true,
    recurringDays: ['周一', '周二', '周三', '周四', '周五'],
    totalSeats: 1,
    availableSeats: 1,
    preferences: ['求1座', '准时到达', '不抽烟', '可提前在门口等'],
    routeHighway: '西铜高架 ➔ 朱宏路 / 凤城八路',
    estimatedMinutes: 40,
    estimatedDistanceKm: 31.0,
    remark: '住在4期公馆，求明早约7:50前往经开区行政中心附近的车主邻居！本人不吸烟不吃东西，非常准时！',
    status: 'active',
    createdAt: '2026-08-15 07:42',
    bookings: [],
  },
  {
    id: 'trip_005',
    type: 'driver_offer',
    direction: 'out_city',
    publisher: {
      id: 'usr_drv_104',
      name: '孙浩天 (晚高峰返程车)',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      gender: 'male',
      phone: '135****4471',
      isVerifiedOwner: true,
      communityPhase: '恒大文旅城·1期天际星空',
      roomNumber: '9号楼1单元2201',
      creditScore: 99,
      completedTripsCount: 83,
      identityTag: '高新中软·认证车主',
    },
    origin: {
      name: '高新·软件新城 (环普科技园/阿里巴巴)',
      detail: '环普三期地库出口或路边',
      zone: '高新区',
    },
    destination: {
      name: '恒大文旅城·1期天际星空门岗',
      detail: '直达小区各期门口下车',
      zone: '恒大文旅城',
    },
    waypoints: [
      { id: 'wp_501', name: '软件新城天谷八路', estimatedTime: '18:40', isPickupAllowed: true },
      { id: 'wp_502', name: '丈八北路地铁口', estimatedTime: '18:55', isPickupAllowed: true },
      { id: 'wp_503', name: '恒大文旅城各期大门', estimatedTime: '19:40', isPickupAllowed: true },
    ],
    departureDate: '2026-08-16',
    departureTime: '18:35',
    isRecurring: true,
    recurringDays: ['周一', '周二', '周三', '周四', '周五'],
    totalSeats: 3,
    availableSeats: 2,
    carInfo: {
      brandModel: '极氪 001 YOU版 极昼白',
      color: '极昼白',
      plateMasked: '陕A·A***9',
      energyType: 'ev',
    },
    preferences: ['下班返程', '晚高峰走绕城', '送至各期大门', '可听轻音乐'],
    routeHighway: '软件新城 ➔ 丈八立交 ➔ 西安绕城 ➔ 正阳大道 ➔ 文旅城',
    estimatedMinutes: 60,
    estimatedDistanceKm: 47.0,
    remark: '晚上下班从软件新城回文旅城，18:35准时发车，沿途可顺路送到1期、2期、3期、公馆大门口，下班一起回家！',
    status: 'active',
    createdAt: '2026-08-15 07:05',
    bookings: [
      {
        id: 'bk_005',
        tripId: 'trip_005',
        passengerId: 'usr_pas_205',
        passengerName: '马建伟',
        passengerAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
        passengerPhone: '137****6619',
        communityPhase: '恒大文旅城·2期',
        seatsBooked: 1,
        pickupPoint: '环普科技园G座',
        dropoffPoint: '恒大文旅城·2期大门',
        notes: '下班带一台轻便电脑包',
        status: 'confirmed',
        createdAt: '2026-08-15 07:22',
        boardingCode: '439218',
      },
    ],
  },
  {
    id: 'trip_006',
    type: 'passenger_request',
    direction: 'out_city',
    publisher: {
      id: 'usr_pas_302',
      name: '杨雅琴 (求晚高峰拼车)',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      gender: 'female',
      phone: '180****7765',
      isVerifiedOwner: true,
      communityPhase: '恒大文旅城·3期童梦汇',
      roomNumber: '4号楼1003',
      creditScore: 100,
      completedTripsCount: 22,
      identityTag: '小寨赛格·认证业主',
    },
    origin: {
      name: '雁塔·小寨十字 (赛格国际购物中心)',
      detail: '赛格南门或长安中路路边',
      zone: '钟楼小寨',
    },
    destination: {
      name: '恒大文旅城·3期童梦汇南门',
      detail: '文旅城3期或周边下车',
      zone: '恒大文旅城',
    },
    waypoints: [],
    departureDate: '2026-08-16',
    departureTime: '19:15',
    isRecurring: false,
    totalSeats: 1,
    availableSeats: 1,
    preferences: ['求1座', '仅限下班返程', '女生友好', '不吸烟'],
    routeHighway: '长安路 ➔ 绕城高速/西铜干线 ➔ 文旅城',
    estimatedMinutes: 50,
    estimatedDistanceKm: 38.0,
    remark: '晚上在小寨赛格下班回恒大文旅城，求顺路回家车主一枚，非常准时！',
    status: 'active',
    createdAt: '2026-08-15 07:15',
    bookings: [],
  },
];

// Community notices & commuter tips
export const COMMUNITY_COMMUTE_TIPS = [
  {
    id: 'tip_1',
    tag: '绕城通畅',
    title: '文旅城至高新 早高峰最佳路线',
    content: '走正阳大道转北三环转绕城高速西段，7:20前通过六村堡立交通行最快，平均省时18分钟。',
  },
  {
    id: 'tip_2',
    tag: '地铁接驳',
    title: '地铁2号线/14号线快速中转指引',
    content: '早高峰拼车至运动公园地铁站仅需约30-35分钟，换乘2号线可无缝直达钟楼、小寨与省体。',
  },
  {
    id: 'tip_3',
    tag: '公益声明',
    title: '恒大文旅城邻里拼车互助守则',
    content: '本程序专为文旅城业主通勤设立，严禁任何形式的营运收费与加价行为，共建和谐文明社区。',
  },
];
